---
- name: Setup Local DevOps Environment
  hosts: localhost       # This playbook runs on the machine where you execute it
  become: yes          # Use sudo to install packages and manage services

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes

    # --- Install Docker ---
    # TODO: Add specific tasks here to install Docker.
    # You'll typically:
    # 1. Install required packages (apt-transport-https, ca-certificates, curl, software-properties-common).
    # 2. Add Docker's official GPG key.
    # 3. Add the Docker APT repository.
    # 4. Install the Docker Engine, CLI, and containerd.io.
    # 5. (Optional) Add your user to the 'docker' group to run docker without sudo.
    - name: Placeholder task for Docker installation
      debug:
        msg: "TODO: Add tasks here to install Docker Engine"

    # --- Install Local Kubernetes (k3s or kind) ---
    # TODO: Add specific tasks here to install k3s or kind.
    # k3s: Use the official installation script or explore community.general.k3s module if available/preferred.
    # kind: Download the binary and move it to a directory in your PATH (e.g., /usr/local/bin).
    - name: Placeholder task for Local K8s installation
      debug:
        msg: "TODO: Add tasks here to install k3s or kind"

    # --- Verification (Optional but Recommended) ---
    # You can add tasks here to verify installations
    # - name: Verify Docker installation
    #   command: docker --version
    #   register: docker_version
    #   changed_when: false
    #   ignore_errors: yes
    # - name: Print Docker version if installed
    #   debug:
    #     var: docker_version.stdout_lines
    #   when: docker_version is success

    # Add similar verification for your K8s tool
