name: CI - Stock UI

on:
  push:
    branches:
      - main
    paths: # Only run this workflow if files in the ui/ directory change
      - 'ui/**'
      - '.github/workflows/ci_ui.yml' # Also run if the workflow file changes
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/ci_ui.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or a recent LTS version

    - name: Install dependencies
      working-directory: ./ui # Run commands from the ui directory
      run: npm ci # 'npm ci' is preferred for clean installs in CI environments

    - name: Run ESLint linter
      working-directory: ./ui
      run: npm run lint # Assumes you added a 'lint' script to package.json

    - name: Run React tests # React apps often come with basic tests
      working-directory: ./ui
      run: npm test -- --watchAll=false # Run tests, exit after completion

    - name: Deploy to GitHub Pages # <--- ADDED THIS DEPLOYMENT STEP
      if: github.ref == 'refs/heads/main' # Only deploy on pushes to main branch
      uses: peaceiris/actions-gh-pages@v3 # Use a popular GitHub Pages deploy action
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this token
        publish_dir: ./ui/dist # Directory containing the built static files (adjust if not 'dist')
        # Optional: Add a CNAME if you have a custom domain
        # cname: example.com