name: CI - Stock UI

on:
  push:
    branches:
      - main
    paths: # Only run this workflow if files in the ui/ directory change
      - 'ui/**'
      - '.github/workflows/ci_ui.yml' # Also run if the workflow file changes
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/ci_ui.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or a recent LTS version

    - name: Install dependencies
      working-directory: ./ui # Run commands from the ui directory
      run: npm ci # 'npm ci' is preferred for clean installs in CI environments

    - name: Run ESLint linter
      working-directory: ./ui
      run: npm run lint # Assumes you added a 'lint' script to package.json

    #- name: Run React tests # React apps often come with basic tests
    #  working-directory: ./ui
      # run: npm test -- --watchAll=false # Run tests, exit after completion

    - name: Deploy to GitHub Pages # <--- This is a step definition
      if: github.ref == 'refs/heads/main' # <--- Step-level key
      uses: peaceiris/actions-gh-pages@v3 # <--- Step-level key
      with: # <--- Parameters for the 'uses' action
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist # Directory containing the built static files (adjust if not 'dist')
        publish_branch: gh-pages # <--- Explicitly state the target branch
        force_orphan: true # <--- Useful for ensuring a clean deploy history
        # Optional: Add a CNAME if you have a custom domain
        # cname: example.com
      working-directory: ./ui # <--- Step-level key (ALIGNED WITH 'uses:' and 'if:')